steps:
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    dir: "notes_fe"

  - name: node:20
    entrypoint: npm
    args: ['run', 'build']
    dir: "notes_fe"
    id: 'npm-build'

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy --quiet
    timeout: 1600s
    id: 'deploy'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1600s
